[versions]
jdbc-postgres-version = "42.7.4"
testcontainers-version = "1.20.4"
logback-version = "1.5.16"

[libraries]
jdbc-postgresql = { module = "org.postgresql:postgresql", version.ref = "jdbc-postgres-version" }
testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "testcontainers-version" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-version" }
